#!/usr/bin/env bash
# code-auditor SessionStart hook — detect installed-plugin drift against the
# shipped manifest.
#
# Board row 7: the installed plugin and the source tree drifted silently in both
# directions (the installed hook-audit.sh gained a scoping block the source
# lacked, while the installed plugin.json/SKILL.md sat a version behind). This
# hook closes the detection gap: at session start it re-hashes every installed
# plugin file and compares each against the `manifest.json` shipped in the same
# package (generated by `scripts/build-manifest.mjs` from the source tree).
#
# Deliberately non-blocking and diagnostic, like hook-warm.sh:
#   - it never fails the session — an install that drifted still works, it just
#     needs a reinstall, and a startup warning must not block the agent;
#   - every failure (missing manifest, unreadable file) is a quiet no-op or a
#     named warning, never an exit-1.
# A drift mismatch is the signal that the install is no longer the source tree's
# single source of truth; the fix is to reinstall (or restore the file).
set -uo pipefail

# Source the shared resolver from this script's own directory — the plugin's
# scripts/ — never from a host environment variable. plugin_root() self-locates
# the plugin root, so an unset or wrong CLAUDE_PLUGIN_ROOT is a non-event.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd)"
. "${SCRIPT_DIR}/hook-common.sh"

ROOT="$(plugin_root)"

# The manifest ships at .claude-plugin/manifest.json; a few installs flatten the
# plugin.json to the plugin root, so check both locations (mirrors
# hook-common.sh's plugin_version).
manifest=""
for f in "${ROOT}/.claude-plugin/manifest.json" "${ROOT}/manifest.json"; do
  if [ -f "$f" ]; then manifest="$f"; break; fi
done
[ -n "${manifest}" ] || exit 0

MANIFEST_PATH="${manifest}" PLUGIN_ROOT="${ROOT}" node <<'NODE'
const fs = require('fs');
const crypto = require('crypto');
const path = require('path');
const manifestPath = process.env.MANIFEST_PATH;
const root = process.env.PLUGIN_ROOT;

let manifest;
try {
  manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
} catch {
  process.exit(0); // unreadable manifest — nothing to compare, stay quiet
}

const files = manifest.files || {};
const problems = [];
for (const [rel, expected] of Object.entries(files)) {
  const abs = path.join(root, rel);
  let actual;
  try {
    actual = crypto.createHash('sha256').update(fs.readFileSync(abs)).digest('hex');
  } catch {
    problems.push(`${rel} (missing)`);
    continue;
  }
  if (actual !== expected) problems.push(rel);
}

if (problems.length > 0) {
  console.error(
    `[code-auditor] installed plugin differs from shipped ${manifest.version || '?'} ` +
    `in ${problems.length} file(s); reinstall the plugin to restore the source tree as ` +
    `the single source of truth:`
  );
  for (const p of problems) console.error(`  - ${p}`);
}
NODE

exit 0
