/**
 * Workflow Guide Tool
 * Provides guidance on optimal tool usage patterns and workflows
 */

export interface WorkflowScenario {
  name: string;
  description: string;
  steps: WorkflowStep[];
  tips?: string[];
}

export interface WorkflowStep {
  order: number;
  tool: string;
  parameters?: Record<string, any>;
  description: string;
  condition?: string;
}

export const WORKFLOW_SCENARIOS: Record<string, WorkflowScenario> = {
  'initial-setup': {
    name: 'Initial Project Setup',
    description: 'First time analyzing a codebase',
    steps: [
      {
        order: 1,
        tool: 'audit',
        parameters: { action: 'start', path: '.', analyzers: ['solid', 'dry', 'documentation'], indexFunctions: true, generateCodeMap: true },
        description: 'Start comprehensive background audit and capture jobId'
      },
      {
        order: 2,
        tool: 'audit',
        parameters: { action: 'status', jobId: 'job_xxx_xxx' },
        description: 'Poll until completed and capture resultId'
      },
      {
        order: 3,
        tool: 'config',
        parameters: { action: 'generate', tools: ['cursor', 'claude'] },
        description: 'Set up AI tool configurations for the project',
        condition: 'If you plan to use AI assistants with this project'
      },
      {
        order: 4,
        tool: 'search',
        parameters: { action: 'query', query: 'TODO FIXME' },
        description: 'Find any outstanding tasks or issues marked in code'
      }
    ],
    tips: [
      'Code maps are generated by default with paginated sections to avoid large responses',
      'The code map shows directory structure, function counts, and documentation quality',
      'Use code_map.get with the returned mapId to view specific sections (overview, files, dependencies, documentation)',
      'Documentation analysis is included by default to check JSDoc coverage',
      'Functions are automatically indexed for future searches',
      'Search operators become available after indexing'
    ]
  },

  'react-development': {
    name: 'React Component Analysis',
    description: 'Analyzing React components and finding specific patterns',
    steps: [
      {
        order: 1,
        tool: 'audit',
        parameters: { action: 'start', path: './src/components', analyzers: ['react', 'documentation'], indexFunctions: true },
        description: 'Start background audit for components directory'
      },
      {
        order: 2,
        tool: 'audit',
        parameters: { action: 'status', jobId: 'job_xxx_xxx' },
        description: 'Poll to completion before reading result pages'
      },
      {
        order: 3,
        tool: 'search',
        parameters: { action: 'query', query: 'entity:component' },
        description: 'List all React components in the codebase'
      },
      {
        order: 4,
        tool: 'search',
        parameters: { action: 'query', query: 'component:functional hook:useState' },
        description: 'Find functional components using state'
      },
      {
        order: 5,
        tool: 'search',
        parameters: { action: 'query', query: 'prop:onClick' },
        description: 'Find components accepting onClick handlers'
      }
    ],
    tips: [
      'Use entity:component to find all React components',
      'Combine operators like component:functional hook:useState',
      'Props are automatically extracted from destructured parameters'
    ]
  },

  'code-review': {
    name: 'Code Review Preparation',
    description: 'Preparing for or conducting a code review',
    steps: [
      {
        order: 1,
        tool: 'audit',
        parameters: { action: 'health', path: './src', threshold: 80, generateCodeMap: true },
        description: 'Quick health check with code map to understand structure and identify issues'
      },
      {
        order: 2,
        tool: 'audit',
        parameters: { action: 'start', path: './src', analyzers: ['solid', 'dry', 'documentation'], minSeverity: 'warning' },
        description: 'Start detailed background audit if health check shows issues',
        condition: 'If health score is below threshold'
      },
      {
        order: 3,
        tool: 'audit',
        parameters: { action: 'status', jobId: 'job_xxx_xxx' },
        description: 'Poll until completed and capture resultId',
        condition: 'After starting detailed audit'
      },
      {
        order: 4,
        tool: 'search',
        parameters: { action: 'query', query: 'complexity:8-10' },
        description: 'Find high complexity functions that may need refactoring'
      },
      {
        order: 5,
        tool: 'search',
        parameters: { action: 'definition', name: 'functionName' },
        description: 'Look up specific function definitions during review'
      }
    ],
    tips: [
      'Code maps provide a visual overview of the codebase structure with paginated sections',
      'Use code_map.get to view specific parts (overview, files, dependencies, documentation)',
      'High complexity functions and poor documentation are flagged in the map',
      'Documentation violations are now included by default in all audits',
      'Functions are indexed during audit for fast lookup'
    ]
  },

  'find-patterns': {
    name: 'Finding Code Patterns',
    description: 'Searching for specific patterns or implementations',
    steps: [
      {
        order: 1,
        tool: 'index',
        parameters: { action: 'sync' },
        description: 'Ensure index is up to date',
        condition: 'If you have made recent changes'
      },
      {
        order: 2,
        tool: 'search',
        parameters: { action: 'query', query: 'natural language query' },
        description: 'Search using natural language (e.g., "validate user input")'
      },
      {
        order: 3,
        tool: 'search',
        parameters: { action: 'query', query: 'lang:typescript file:utils' },
        description: 'Use operators to filter results'
      }
    ],
    tips: [
      'Natural language search uses synonym expansion',
      'Combine text search with operators for precision',
      'Use search.definition for exact function lookup'
    ]
  },

  'maintenance': {
    name: 'Codebase Maintenance',
    description: 'Regular maintenance and cleanup tasks',
    steps: [
      {
        order: 1,
        tool: 'audit',
        parameters: { action: 'start', path: '.', analyzers: ['solid', 'dry', 'documentation', 'security'] },
        description: 'Start full background audit to identify issues'
      },
      {
        order: 2,
        tool: 'audit',
        parameters: { action: 'status', jobId: 'job_xxx_xxx' },
        description: 'Poll until completed and use resultId for paged reads'
      },
      {
        order: 3,
        tool: 'search',
        parameters: { action: 'query', query: 'console.log debug' },
        description: 'Find debug statements to remove'
      },
      {
        order: 4,
        tool: 'index',
        parameters: { action: 'cleanup' },
        description: 'Clean up stale entries from deleted files'
      }
    ],
    tips: [
      'Regular audits help maintain code quality',
      'index.cleanup removes entries for deleted files',
      'Search for common antipatterns like console.log'
    ]
  },

  'understand-codebase': {
    name: 'Understanding Codebase Structure',
    description: 'Getting oriented in a new or unfamiliar codebase',
    steps: [
      {
        order: 1,
        tool: 'audit',
        parameters: { action: 'health', path: '.', generateCodeMap: true },
        description: 'Generate a code map to understand overall structure and architecture'
      },
      {
        order: 2,
        tool: 'search',
        parameters: { action: 'query', query: 'entity:component' },
        description: 'List all React components to understand UI architecture'
      },
      {
        order: 3,
        tool: 'search',
        parameters: { action: 'query', query: 'depends-on:database deps:prisma' },
        description: 'Find data access patterns and database usage'
      },
      {
        order: 4,
        tool: 'search',
        parameters: { action: 'query', query: 'file:route file:api' },
        description: 'Locate API endpoints and routing logic'
      }
    ],
    tips: [
      'Code maps show directory structure, complexity, and documentation quality at a glance',
      'Maps are now paginated - use code_map.get to view specific sections',
      'Start with the overview section to understand architectural patterns',
      'Use dependency searches to trace data flow',
      'File path searches help locate specific functionality'
    ]
  },

  'large-audit-handling': {
    name: 'Handling Large Audits',
    description: 'Working with large codebases using async audit jobs and paged result fetches',
    steps: [
      {
        order: 1,
        tool: 'audit',
        parameters: { action: 'start', path: '.', analyzers: ['solid'], minSeverity: 'warning', analyzerConcurrency: 2 },
        description: 'Start a background audit and get a jobId immediately'
      },
      {
        order: 2,
        tool: 'audit',
        parameters: { action: 'status', jobId: 'job_xxx_xxx' },
        description: 'Poll until status is completed and capture resultId',
        condition: 'Repeat while status is queued or running'
      },
      {
        order: 3,
        tool: 'audit',
        parameters: { action: 'results', resultId: 'audit_xxx_xxx', offset: 0, limit: 25 },
        description: 'Fetch first page of violations with resultId'
      },
      {
        order: 4,
        tool: 'audit',
        parameters: { action: 'results', resultId: 'audit_xxx_xxx', offset: 25, limit: 25 },
        description: 'Fetch next pages using offset/limit only',
        condition: 'When pagination.hasMore is true'
      }
    ],
    tips: [
      'Use minSeverity:"warning" to filter out info-level suggestions',
      'audit.start is non-blocking; heavy work runs in the background',
      'audit.status returns resultId only when the run is completed',
      'audit.results is read-only and never starts a new audit',
      'Use analyzerConcurrency:2 or 3 for faster runs on large projects',
      'Tune workerCount and maxRetries for large shard-heavy audits'
    ]
  },

  'code-map-exploration': {
    name: 'Code Map Exploration',
    description: 'Working with paginated code maps to understand codebase structure',
    steps: [
      {
        order: 1,
        tool: 'audit',
        parameters: { action: 'health', path: '.', generateCodeMap: true },
        description: 'Generate a paginated code map during health check'
      },
      {
        order: 2,
        tool: 'code_map',
        parameters: { action: 'list', mapId: 'map_xxx_xxx' },
        description: 'List all available sections in the generated code map'
      },
      {
        order: 3,
        tool: 'code_map',
        parameters: { action: 'get', mapId: 'map_xxx_xxx', sectionType: 'overview' },
        description: 'View the overview section for high-level structure and metrics'
      },
      {
        order: 4,
        tool: 'code_map',
        parameters: { action: 'get', mapId: 'map_xxx_xxx', sectionType: 'files' },
        description: 'View detailed file analysis with complexity and documentation scores'
      },
      {
        order: 5,
        tool: 'code_map',
        parameters: { action: 'get', mapId: 'map_xxx_xxx', sectionType: 'documentation' },
        description: 'View documentation analysis with specific violations and suggestions'
      }
    ],
    tips: [
      'Code maps are automatically paginated to avoid overwhelming responses',
      'The mapId is returned in the initial audit response for section retrieval',
      'Each section provides focused information: overview (stats), files (detailed analysis), dependencies (imports/exports), documentation (JSDoc violations)',
      'Use code_map.list to see all available sections and their sizes',
      'Code maps are stored in-memory and cleared when the server restarts'
    ]
  },

  'analyzer-configuration': {
    name: 'Analyzer Configuration',
    description: 'Configuring analyzer tolerances and managing exceptions',
    steps: [
      {
        order: 1,
        tool: 'config',
        parameters: { action: 'get' },
        description: 'Check current analyzer configurations'
      },
      {
        order: 2,
        tool: 'config',
        parameters: {
          action: 'set',
          analyzerName: 'solid',
          config: {
            maxUnrelatedResponsibilities: 3,
            maxMethodsPerClass: 20,
            contextAwareThresholds: true
          }
        },
        description: 'Set custom tolerances for SOLID analyzer',
        condition: 'When default thresholds are too strict for your architecture'
      },
      {
        order: 3,
        tool: 'config',
        parameters: {
          action: 'set',
          analyzerName: 'dry',
          config: {
            minLineThreshold: 15,
            similarityThreshold: 0.85
          }
        },
        description: 'Adjust DRY analyzer for less strict duplication detection',
        condition: 'When you have legitimate repeated patterns'
      },
      {
        order: 4,
        tool: 'config',
        parameters: { action: 'whitelist_detect', path: '.', autoPopulate: false },
        description: 'Detect framework patterns for whitelisting'
      },
      {
        order: 5,
        tool: 'config',
        parameters: { action: 'whitelist_add', name: 'MyContextProvider', type: 'framework-class' },
        description: 'Add specific exceptions for framework patterns'
      },
      {
        order: 6,
        tool: 'audit',
        parameters: { action: 'start', path: '.', analyzers: ['solid', 'dry'] },
        description: 'Re-run audit with new configurations'
      }
    ],
    tips: [
      'Analyzer configs persist across all audit runs',
      'Use config.set once, benefit everywhere',
      'Project-specific configs override global configs',
      'Context-aware thresholds auto-adjust for component patterns',
      'Combine whitelist and config for fine-grained control',
      'Use config.reset to revert to defaults'
    ]
  },

  'tolerance-configuration': {
    name: 'Tolerance Configuration',
    description: 'Setting up custom tolerances for your project architecture',
    steps: [
      {
        order: 1,
        tool: 'audit',
        parameters: { action: 'start', path: '.', analyzers: ['solid'] },
        description: 'Start initial background audit to see default violations'
      },
      {
        order: 2,
        tool: 'config',
        parameters: { action: 'get', analyzerName: 'solid' },
        description: 'Check current SOLID configuration'
      },
      {
        order: 3,
        tool: 'config',
        parameters: {
          action: 'set',
          analyzerName: 'solid',
          config: {
            maxUnrelatedResponsibilities: 4,
            maxMethodsPerClass: 25,
            maxInterfaceMembers: 30,
            contextAwareThresholds: true,
            checkUnrelatedResponsibilities: false,
            patternThresholds: {
              Layout: { maxResponsibilities: 4 },
              Dashboard: { maxResponsibilities: 6 },
              SimpleUI: { maxResponsibilities: 2 }
            }
          }
        },
        description: 'Relax SOLID thresholds with pattern-specific overrides',
        condition: 'If you have Context Providers or Dashboard components'
      },
      {
        order: 4,
        tool: 'config',
        parameters: {
          action: 'set',
          analyzerName: 'solid',
          projectPath: '/path/to/project',
          config: { maxUnrelatedResponsibilities: 5 }
        },
        description: 'Set project-specific override for even more tolerance',
        condition: 'For specific projects with unique architecture'
      },
      {
        order: 5,
        tool: 'audit',
        parameters: { action: 'start', path: '.', analyzers: ['solid'] },
        description: 'Re-run audit to validate reduced violations'
      }
    ],
    tips: [
      'Start with small adjustments and increase if needed',
      'Use patternThresholds to override multipliers for specific patterns',
      'Set checkUnrelatedResponsibilities: false to disable unrelated groups check',
      'Dashboard components get 2x multiplier by default (unless overridden)',
      'Project configs override global configs',
      'Use config.get without params to see all configs'
    ]
  },

  'dependency-analysis': {
    name: 'Dependency Analysis',
    description: 'Analyzing dependencies and refactoring impact',
    steps: [
      {
        order: 1,
        tool: 'audit',
        parameters: { action: 'start', path: '.', indexFunctions: true },
        description: 'Start background audit to ensure functions are indexed with dependency tracking'
      },
      {
        order: 2,
        tool: 'search',
        parameters: { action: 'query', query: 'dep:lodash' },
        description: 'Find all functions using a specific dependency',
        condition: 'To see impact of updating/removing a package'
      },
      {
        order: 3,
        tool: 'search',
        parameters: { action: 'query', query: 'calls:calculateTotal' },
        description: 'Find all functions that call a specific function',
        condition: 'To understand impact before refactoring'
      },
      {
        order: 4,
        tool: 'search',
        parameters: { action: 'query', query: 'dependents-of:authenticate' },
        description: 'Find what depends on a function you want to change'
      },
      {
        order: 5,
        tool: 'search',
        parameters: { action: 'query', query: 'unused-imports' },
        description: 'Find and clean up unused imports with improved accuracy'
      }
    ],
    tips: [
      'Use dep: to find all usages of an external library',
      'Use calls: to trace function call chains',
      'Use dependents-of: to see what will be affected by changes',
      'Combine with file: to limit scope (e.g., "dep:react file:components")',
      'unused-imports helps reduce bundle size',
      'Improved type detection reduces false positives for type-only imports'
    ]
  }
};

export function getWorkflowGuide(scenario?: string): WorkflowScenario | Record<string, WorkflowScenario> {
  if (scenario) {
    const workflow = WORKFLOW_SCENARIOS[scenario];
    if (!workflow) {
      throw new Error(`Unknown workflow scenario: ${scenario}. Available: ${Object.keys(WORKFLOW_SCENARIOS).join(', ')}`);
    }
    return workflow;
  }
  return WORKFLOW_SCENARIOS;
}

export function getWorkflowTips(): Record<string, string[]> {
  return {
    'general': [
      'Start audits explicitly with audit.start (no implicit long-running scans)',
      'Use audit.health for quick checks before detailed analysis',
      'Documentation analysis is now included by default in all audits',
      'Code maps are generated by default with paginated sections',
      'Combine natural language with operators in search queries',
      'React components are automatically detected in .tsx/.jsx files',
      'Improved TypeScript support with better type-only import detection',
      'Poll audit.status and use resultId once status is completed',
      'Audit results are paginated - use audit.results with limit and offset',
      'Analyzer configs persist - set once, use everywhere',
      'Use config.set to adjust tolerances for your architecture'
    ],
    'search-operators': [
      'entity:component - Find all React components',
      'component:functional|class - Filter by component type',
      'hook:hookName - Find components using specific hooks',
      'prop:propName - Find components with specific props',
      'complexity:5-10 - Filter by complexity range',
      'Combine operators: "Button component:functional hook:useState"'
    ],
    'performance': [
      'Index is built during audit, no separate indexing needed',
      'Use specific paths in audit to analyze only changed code',
      'search.query is fast even on large codebases',
      'search.definition is optimized for exact name lookup',
      'For partitioned runs, workerCount scales shard execution across CPU cores',
      'Use shardTimeoutMs and maxRetries to balance resilience vs. latency'
    ],
    'pagination': [
      'Default limit is 50 violations per request (max 100)',
      'Use offset parameter to get subsequent pages',
      'Run audit.start, then poll audit.status for completion',
      'When completed, use audit.status.resultId with audit.results',
      'Example: audit.results(resultId: "...", offset: 25, limit: 25)',
      'Cached results expire after 24 hours'
    ],
    'analyzer-config': [
      'config.set persists settings across all audits',
      'Global configs apply to all projects by default',
      'Project-specific configs override global ones',
      'maxUnrelatedResponsibilities controls component complexity',
      'contextAwareThresholds auto-adjusts for patterns (Dashboard, Form, etc)',
      'Use config.get to check current settings',
      'config.reset reverts to defaults'
    ],
    'code-maps': [
      'Code maps are paginated automatically to manage response sizes',
      'Use code_map.get with mapId to view specific sections',
      'Available sections: overview, files, dependencies, documentation',
      'code_map.list shows all available sections and their sizes',
      'Maps are stored in-memory and cleared on server restart',
      'generateCodeMap defaults to true in audit and audit.health tools'
    ]
  };
}
